makros_setup: |
  author: "Volker Göhler, Niklas Werner"
  email: "volker.goehler@informatik.tu-freiberg"
  version: "0.2.6"
  edit: true
  title: "DiAgnostiK Holzarten Makros"
  tags: "Wissensspeicher"
  
  @diagnostik_image: <div class="image-container" style="height: @2rem; width: @2rem;"><img src="@0/@1" alt="@1"></div>
  
  @style
  .image-container {
    width: 200px;
    height: 200px;
    border: 1px solid #ccc;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    background-color: #f8f8f8;
  }
  
  .image-container img {
    width: fit-content;
    height: fit-content;
    object-fit: contain;
  }
  @end

repository: "https://github.com/Ifi-DiAgnostiK-Project/Holzarten"
makro_file: "makros.md"
image_folder: "img"

# use raw_location to place the location to the file
how_to_use: |
  # Link zu LiaScript
  [![LiaScript Course](https://raw.githubusercontent.com/LiaScript/LiaScript/master/badges/course.svg)](https://liascript.github.io/course/?{raw_location})
  
  > Diese Datei ist automatisch generiert und enthält Makros für die DiAgnostiK-Holzartenbilder.
  
  # Anleitung
  > Der Befehl zum einbinden eines Bildes lautet `@<Bereich>.<Name>(Größe)`.
  > Hängt man statt der Größe `.src` an, so wird der Link zum Bild angezeigt. `@<Bereich>.<Name>.src`

  - Der Bereich ist der Ordnername, in dem sich das Bild befindet.
  - Der Name ist der Dateiname ohne Endung.
  - Die Größe ist in Zeilen angegeben, die das Bild hoch sein soll.

  Alle Bilder sowie ihre Bereiche und die Befehle um sie zu laden sind in den Tabellen weiter unten abgebildet.

  **Die Anzeige benötigt LiaScript!**
  
  ## Beispiel
  
  `@Hoelzer2.Laerche(10)`

  @Hoelzer2.Laerche(10)

  `@Hoelzer2.Laerche.src`

  @Hoelzer2.Laerche.src

  ## Bereiche und Befehle

  Im Nachfolgenden sind alle Bilder aller Bereiche und passende Befehle aufgelistet, die in dieser Sammlung enthalten sind. 

